name: Bug Report
description: Report an Issue or Bug with the Module
title: "[Bug]: "
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              We're sorry to hear you have a problem. Can you help us solve it by providing the following details.
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: What did you expect to happen?
          placeholder: I cannot currently do X thing because when I do, it breaks X thing.
      validations:
          required: true
    - type: textarea
      id: how-to-reproduce
      attributes:
          label: How to reproduce the bug
          description: How did this occur, please add any config values used and provide a set of reliable steps if possible.
          placeholder: When I do X I see Y.
      validations:
          required: true
    - type: input
      id: module-version
      attributes:
          label: Module Version
          description: What version of the module are you running?
          placeholder: 1.0.0
      validations:
          required: true
    - type: input
      id: php-version
      attributes:
          label: PHP Version
          description: What version of PHP are you running?
          placeholder: 8.2.0
      validations:
          required: true
    - type: input
      id: xoops-version
      attributes:
          label: XOOPS Version
          description: What version of XOOPS CMS are you running?
          placeholder: 2.5.12
      validations:
          required: true
    - type: dropdown
      id: operating-systems
      attributes:
        label: Which operating systems does this happen with?
        description: You may select more than one.
        multiple: true
        options:
        - Linux
        - Windows
        - macOS
    - type: textarea
      id: notes
      attributes:
          label: Notes
          description: Use this field to provide any other notes that you feel might be relevant to the issue.
      validations:
          required: false
